-- ============================================================================
-- Task to run dbt transformations when new data arrives - PROD Environment
-- This task checks the stream and runs dbt when new data is detected
-- ============================================================================

CREATE TASK IF NOT EXISTS ANALYTICS.TASK_DBT_TRANSFORMATIONS_PROD
WAREHOUSE = APEXML_PROD_WH
SCHEDULE = 'USING CRON 0 9 * * SAT UTC'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STREAM_DBT_TRANSFORMATIONS_PROD')
AS
CALL ANALYTICS.STORED_PROCEDURE_DBT_TRANSFORMATIONS_PROD();

-- Grant permissions
GRANT OPERATE ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_PROD TO ROLE APEXML_PROD_ADMIN;
GRANT MONITOR ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_PROD TO ROLE APEXML_PROD_ADMIN;
GRANT MONITOR ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_PROD TO ROLE APEXML_PROD_READ;

-- Start the task (must be done explicitly)
-- ALTER TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_PROD RESUME;

-- To check task status:
-- SHOW TASKS LIKE 'TASK_DBT_TRANSFORMATIONS_PROD';
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) WHERE NAME = 'TASK_DBT_TRANSFORMATIONS_PROD' ORDER BY SCHEDULED_TIME DESC LIMIT 10;
