-- ============================================================================
-- Task to run dbt transformations when new data arrives - DEV Environment
-- This task checks the stream and runs dbt when new data is detected
-- ============================================================================

CREATE TASK IF NOT EXISTS ANALYTICS.TASK_DBT_TRANSFORMATIONS_DEV
WAREHOUSE = APEXML_DEV_WH
SCHEDULE = 'USING CRON 0 9 * * SAT UTC'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STREAM_DBT_TRANSFORMATIONS_DEV')
AS
CALL ANALYTICS.STORED_PROCEDURE_DBT_TRANSFORMATIONS_DEV();

-- Grant permissions
GRANT OPERATE ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_DEV TO ROLE APEXML_DEV_ADMIN;
GRANT MONITOR ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_DEV TO ROLE APEXML_DEV_ADMIN;
GRANT MONITOR ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_DEV TO ROLE APEXML_DEV_READ;

-- Start the task (must be done explicitly)
-- ALTER TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_DEV RESUME;

-- To check task status:
-- SHOW TASKS LIKE 'TASK_DBT_TRANSFORMATIONS_DEV';
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) WHERE NAME = 'TASK_DBT_TRANSFORMATIONS_DEV' ORDER BY SCHEDULED_TIME DESC LIMIT 10;
