-- ============================================================================
-- Task to run dbt transformations when new data arrives - STAGING Environment
-- This task checks the stream and runs dbt when new data is detected
-- ============================================================================

CREATE TASK IF NOT EXISTS ANALYTICS.TASK_DBT_TRANSFORMATIONS_STAGING
WAREHOUSE = APEXML_STAGING_WH
SCHEDULE = 'USING CRON 0 9 * * SAT UTC'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STREAM_DBT_TRANSFORMATIONS_STAGING')
AS
CALL ANALYTICS.STORED_PROCEDURE_DBT_TRANSFORMATIONS_STAGING();

-- Grant permissions
GRANT OPERATE ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_STAGING TO ROLE APEXML_STAGING_ADMIN;
GRANT MONITOR ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_STAGING TO ROLE APEXML_STAGING_ADMIN;
GRANT MONITOR ON TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_STAGING TO ROLE APEXML_STAGING_READ;

-- Start the task (must be done explicitly)
-- ALTER TASK ANALYTICS.TASK_DBT_TRANSFORMATIONS_STAGING RESUME;

-- To check task status:
-- SHOW TASKS LIKE 'TASK_DBT_TRANSFORMATIONS_STAGING';
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) WHERE NAME = 'TASK_DBT_TRANSFORMATIONS_STAGING' ORDER BY SCHEDULED_TIME DESC LIMIT 10;
