name: 'apexml'
version: '1.0.0'
config-version: 2

profile: 'apexml'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  apexml:
    staging:
      +materialized: view
      +schema: staging
    analytics:
      +materialized: table
      +schema: analytics
