version: 2

sources:
  - name: raw
    description: Raw data from OpenF1 API
    database: APEXML_DEV
    schema: RAW
    tables:
      - name: sessions
        description: F1 session data (Practice, Qualifying, Race)
        columns:
          - name: session_key
            description: Unique session identifier
          - name: session_type
            description: Type of session
          - name: date_start
            description: Session start timestamp

      - name: drivers
        description: F1 driver information
        columns:
          - name: driver_number
            description: Driver racing number
          - name: full_name
            description: Driver full name

      - name: laps
        description: Lap times and telemetry
        columns:
          - name: session_key
            description: Session identifier
          - name: lap_duration
            description: Lap time in seconds

      - name: positions
        description: Lap-by-lap position data
        columns:
          - name: session_key
            description: Session identifier
          - name: position
            description: Track position
