import os
from pathlib import Path

def extract_docstring(file_path: str) -> str:
    """Extract the first module-level docstring from a Python file."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    for quote in ('"""', "'''"):
        if quote in content:
            start = content.find(quote) + 3
            end = content.find(quote, start)
            if end > start:
                return content[start:end].strip()
    return "No module docstring found."

def generate_readme():
    project_name = Path.cwd().name
    py_files = sorted(
        [f for f in os.listdir() if f.endswith(".py") and f != "scripts/generate_readme.py"]
    )

    readme = [
        f"# {project_name}",
        "",
        "## Project Overview",
        "",
        "This README is automatically generated by reading Python source files.",
        "",
    ]

    if py_files:
        readme.append("## Python Modules")
        readme.append("")
        for file in py_files:
            doc = extract_docstring(file)
            readme.append(f"### `{file}`")
            readme.append("")
            readme.append(doc)
            readme.append("")

    req_path = Path(__file__).resolve().parent.parent / "requirements.txt"
    readme.append("## Dependencies")
    readme.append("")

    if req_path.exists():
        with open(req_path, "r", encoding="utf-8") as f:
            deps = [line.strip() for line in f if line.strip()]
        if deps:
            for dep in deps:
                readme.append(f"- {dep}")
        else:
            readme.append("_No dependencies listed._")
    else:
        readme.append("_No requirements.txt file found._")

    readme.append("")
    readme.append("---")
    readme.append("README auto-generated via GitHub Actions.")

    Path("README.md").write_text("\\n".join(readme), encoding="utf-8")
    print("README.md generated successfully.")

if __name__ == "__main__":
    generate_readme()
