-- ========================================
-- Snowflake Role Hierarchy & Grants Setup
-- ========================================
-- Run this script after Terraform creates the infrastructure
-- This sets up RBAC that was removed from Terraform due to deprecated resources

USE ROLE ACCOUNTADMIN;

-- ========================================
-- 1. ROLE HIERARCHY
-- ========================================
-- ACCOUNTADMIN → SYSADMIN → DATA_ENGINEER → ANALYTICS_USER, ML_ENGINEER

-- Grant DATA_ENGINEER to SYSADMIN
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;

-- Grant ANALYTICS_USER and ML_ENGINEER to DATA_ENGINEER
GRANT ROLE ANALYTICS_USER TO ROLE DATA_ENGINEER;
GRANT ROLE ML_ENGINEER TO ROLE DATA_ENGINEER;

-- ========================================
-- 2. DATABASE GRANTS
-- ========================================

-- Grant USAGE on database to DATA_ENGINEER
GRANT USAGE ON DATABASE APEXML_DEV TO ROLE DATA_ENGINEER;

-- Grant USAGE on database to ANALYTICS_USER (read-only)
GRANT USAGE ON DATABASE APEXML_DEV TO ROLE ANALYTICS_USER;

-- Grant USAGE on database to ML_ENGINEER
GRANT USAGE ON DATABASE APEXML_DEV TO ROLE ML_ENGINEER;

-- ========================================
-- 3. SCHEMA GRANTS - RAW
-- ========================================

-- DATA_ENGINEER: Full access to RAW schema
GRANT ALL PRIVILEGES ON SCHEMA APEXML_DEV.RAW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APEXML_DEV.RAW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APEXML_DEV.RAW TO ROLE DATA_ENGINEER;

-- ========================================
-- 4. SCHEMA GRANTS - STAGING
-- ========================================

-- DATA_ENGINEER: Full access to STAGING schema
GRANT ALL PRIVILEGES ON SCHEMA APEXML_DEV.STAGING TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APEXML_DEV.STAGING TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA APEXML_DEV.STAGING TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APEXML_DEV.STAGING TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA APEXML_DEV.STAGING TO ROLE DATA_ENGINEER;

-- ANALYTICS_USER: Read-only access to STAGING
GRANT USAGE ON SCHEMA APEXML_DEV.STAGING TO ROLE ANALYTICS_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA APEXML_DEV.STAGING TO ROLE ANALYTICS_USER;
GRANT SELECT ON ALL VIEWS IN SCHEMA APEXML_DEV.STAGING TO ROLE ANALYTICS_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA APEXML_DEV.STAGING TO ROLE ANALYTICS_USER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA APEXML_DEV.STAGING TO ROLE ANALYTICS_USER;

-- ========================================
-- 5. SCHEMA GRANTS - ANALYTICS
-- ========================================

-- DATA_ENGINEER: Full access to ANALYTICS schema
GRANT ALL PRIVILEGES ON SCHEMA APEXML_DEV.ANALYTICS TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA APEXML_DEV.ANALYTICS TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA APEXML_DEV.ANALYTICS TO ROLE DATA_ENGINEER;

-- ANALYTICS_USER: Read-only access to ANALYTICS
GRANT USAGE ON SCHEMA APEXML_DEV.ANALYTICS TO ROLE ANALYTICS_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA APEXML_DEV.ANALYTICS TO ROLE ANALYTICS_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA APEXML_DEV.ANALYTICS TO ROLE ANALYTICS_USER;

-- ML_ENGINEER: Read access to ANALYTICS schema
GRANT USAGE ON SCHEMA APEXML_DEV.ANALYTICS TO ROLE ML_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA APEXML_DEV.ANALYTICS TO ROLE ML_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA APEXML_DEV.ANALYTICS TO ROLE ML_ENGINEER;

-- ========================================
-- 6. WAREHOUSE GRANTS
-- ========================================

-- DATA_ENGINEER: Can use ETL warehouse
GRANT USAGE ON WAREHOUSE ETL_WH_DEV TO ROLE DATA_ENGINEER;

-- ANALYTICS_USER: Can use analytics warehouse
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_DEV TO ROLE ANALYTICS_USER;

-- ML_ENGINEER: Can use analytics warehouse
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_DEV TO ROLE ML_ENGINEER;

-- ========================================
-- 7. USER ROLE ASSIGNMENTS
-- ========================================

-- Grant DATA_ENGINEER role to ETL service account
GRANT ROLE DATA_ENGINEER TO USER ETL_SERVICE_ACCOUNT;

-- ========================================
-- 8. VERIFICATION QUERIES
-- ========================================

-- Verify role hierarchy
SHOW GRANTS TO ROLE DATA_ENGINEER;
SHOW GRANTS TO ROLE ANALYTICS_USER;
SHOW GRANTS TO ROLE ML_ENGINEER;

-- Verify user grants
SHOW GRANTS TO USER ETL_SERVICE_ACCOUNT;

-- Check role hierarchy visually
SELECT
    GRANTEE_NAME AS role,
    NAME AS granted_role,
    GRANTED_BY
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE GRANTED_ON = 'ROLE'
    AND GRANTEE_NAME IN ('SYSADMIN', 'DATA_ENGINEER', 'ANALYTICS_USER', 'ML_ENGINEER')
ORDER BY role, granted_role;

SHOW ROLES;
